### ISSUE TITLE
Data Model ->  CRUD API

### ISSUE THREAD

**Issue by ahalls** [GaltSoft/kitura-manager#3]
Register the End Points to support the CRUD transactions on the data model

Provide an API for registering Callbacks for each of the endpoints

**Comment by the-freshlord** [comment]
Any initial ideas on how you think we can approach this?

**Comment by ahalls** [comment]
@eman6576 My Ideas
For this task assume we have an internal representation of the entity and attributes
Entity Name
Attribute Name
Attribute Type. (.integer or .string)
Then there is an array of Attributes
form this I think you can register endpoints for the CRUD API
have callback methods for each action

Unit test that demonstrates that works

**Comment by the-freshlord** [comment]
Do want to also connect the entity to a datasource as well? For example, a developer can create an entity called User and they choose to connect it to a MySQL datasource.

**Comment by the-freshlord** [comment]
Also would they provide a JSON file or do we want to use a Swift file for this?

**Comment by ahalls** [comment]
Yes we are going to connect to a data source.  My idea is we do that with an ORM  that is what issue #4 and #5 are about.  That way we can support any database the ORM does ... like MySQL, Postgress, CouchDB etc  ...

**Comment by ahalls** [comment]
I would like to avoid having to have a JSON Definition file ... I would like to get the definition directly out of the Class Definition.  That is what @KingAndroid  is working on in issue #6
